/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TransactionRecord = IDL.Record({
  'id' : IDL.Nat,
  'fromAccount' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Nat,
  'toAccount' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Account = IDL.Record({
  'balance' : IDL.Nat,
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'idDocumentNumber' : IDL.Text,
  'address' : IDL.Text,
  'customerId' : IDL.Text,
  'accountNumber' : IDL.Text,
  'transactionHistory' : IDL.Vec(TransactionRecord),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deposit' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getAccount' : IDL.Func([IDL.Principal], [IDL.Opt(Account)], ['query']),
  'getCallerAccount' : IDL.Func([], [IDL.Opt(Account)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTransactionHistory' : IDL.Func(
      [],
      [IDL.Vec(TransactionRecord)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerAccount' : IDL.Func([Account], [], []),
  'transfer' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TransactionRecord = IDL.Record({
    'id' : IDL.Nat,
    'fromAccount' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Nat,
    'toAccount' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Account = IDL.Record({
    'balance' : IDL.Nat,
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'idDocumentNumber' : IDL.Text,
    'address' : IDL.Text,
    'customerId' : IDL.Text,
    'accountNumber' : IDL.Text,
    'transactionHistory' : IDL.Vec(TransactionRecord),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deposit' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getAccount' : IDL.Func([IDL.Principal], [IDL.Opt(Account)], ['query']),
    'getCallerAccount' : IDL.Func([], [IDL.Opt(Account)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTransactionHistory' : IDL.Func(
        [],
        [IDL.Vec(TransactionRecord)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerAccount' : IDL.Func([Account], [], []),
    'transfer' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };