/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'balance' : bigint,
  'dateOfBirth' : string,
  'name' : string,
  'idDocumentNumber' : string,
  'address' : string,
  'customerId' : string,
  'accountNumber' : string,
  'transactionHistory' : Array<TransactionRecord>,
}
export interface TransactionRecord {
  'id' : bigint,
  'fromAccount' : string,
  'description' : string,
  'timestamp' : bigint,
  'toAccount' : string,
  'amount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deposit' : ActorMethod<[string, bigint], undefined>,
  'getAccount' : ActorMethod<[Principal], [] | [Account]>,
  'getCallerAccount' : ActorMethod<[], [] | [Account]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTransactionHistory' : ActorMethod<[], Array<TransactionRecord>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerAccount' : ActorMethod<[Account], undefined>,
  'transfer' : ActorMethod<[string, string, bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];